[[bin]]
name = "filesync"
path = "src/main.rs"

[package]
name = "notify-demo"
version = "2025.1.17"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
filetime = "0.2"
libc = "0.2"
notify = "6"